<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="CurrentBPUpdate" Id="{8b324aa8-068c-4257-be00-af3f86b96ed0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM CurrentBPUpdate
VAR
	{attribute 'pytmc' := '
		pv: @(PREFIX)MPS:KickerPermRate
		link: IOC:BSY0:MP01:BYKIK_RATE
	'}
	nBeamRate : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="CurrentBPUpdate">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>